version: '3.3'

services: 
  db_web_server:
    build: ./web_server
    environment: 
      - APP_NAME="Reservasi"
      - DB_HOST=192.168.17.30
      - DB_PORT=3306
      - DB_DATABASE=reservasi
      - DB_USERNAME=haproxy_root
      - DB_PASSWORD=admin
    volumes: 
      - ./web_server/log:/var/log/apache2
      - ./web_server/root:/root
    depends_on: 
      - db_server_1
      - db_load_balancer
    networks: 
      bdt_network:
        ipv4_address: 192.168.17.29
    ports: 
      - "80:80"
    command: /bin/bash -c "/bin/bash /root/startup.sh; tail -f /dev/null"

  db_load_balancer:
    build: ./db_load_balancer
    volumes: 
      - ./db_load_balancer/log:/var/log/haproxy
      - ./db_load_balancer/root:/root
    networks: 
      bdt_network:
        ipv4_address: 192.168.17.30
    ports: 
      - "3306:3306"
      - "9201:9201"
    command: /bin/bash -c "/bin/bash /root/startup.sh; tail -f /dev/null"

  db_server_1:
    build: ./db_server
    environment: 
      - SERVER_ID=1
      - SERVER_IP=192.168.17.31
      - SERVER_REPLICATION_PORT=33061
      - GROUP_NAME="d0e43142-3131-4673-82d4-7eef36586372"
      - IP_WHITELIST="192.168.17.31, 192.168.17.32, 192.168.17.33"
      - GROUP_SEEDS="192.168.17.31:33061, 192.168.17.32:33061, 192.168.17.33:33061"
    volumes: 
      - db_server1:/var/lib/mysql
      - ./db_server/log/1:/var/log/mysql
      - ./db_server/root:/root
    networks: 
      bdt_network:
        ipv4_address: 192.168.17.31
    command: /bin/bash -c "/bin/bash /root/startup.sh; tail -f /dev/null"

  db_server_2:
    build: ./db_server
    environment: 
      - SERVER_ID=2
      - SERVER_IP=192.168.17.32
      - SERVER_REPLICATION_PORT=33061
      - GROUP_NAME="d0e43142-3131-4673-82d4-7eef36586372"
      - IP_WHITELIST="192.168.17.31, 192.168.17.32, 192.168.17.33"
      - GROUP_SEEDS="192.168.17.31:33061, 192.168.17.32:33061, 192.168.17.33:33061"
    volumes: 
      - db_server2:/var/lib/mysql
      - ./db_server/log/2:/var/log/mysql
      - ./db_server/root:/root
    depends_on: 
      - db_server_1
    networks: 
      bdt_network:
        ipv4_address: 192.168.17.32
    command: /bin/bash -c "/bin/bash /root/startup.sh; tail -f /dev/null"
    
  db_server_3:
    build: ./db_server
    environment: 
      - SERVER_ID=3
      - SERVER_IP=192.168.17.33
      - SERVER_REPLICATION_PORT=33061
      - GROUP_NAME="d0e43142-3131-4673-82d4-7eef36586372"
      - IP_WHITELIST="192.168.17.31, 192.168.17.32, 192.168.17.33"
      - GROUP_SEEDS="192.168.17.31:33061, 192.168.17.32:33061, 192.168.17.33:33061"
    volumes: 
      - db_server3:/var/lib/mysql
      - ./db_server/log/3:/var/log/mysql
      - ./db_server/root:/root
    depends_on: 
      - db_server_1
    networks: 
      bdt_network:
        ipv4_address: 192.168.17.33
    command: /bin/bash -c "/bin/bash /root/startup.sh; tail -f /dev/null"

volumes: 
  db_server1: {}
  db_server2: {}
  db_server3: {}

networks:
  bdt_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.17.0/24